tf_redis:
  image: redis
  ports:
    - "6379"

tf_sidekiq:
  build: .
  command: bundle exec sidekiq
  links:
    - tf_redis

tf_api:
  build: .
  command: bundle exec puma
  ports:
    - "81:3001"
  links:
    - tf_redis
