source 'https://rubygems.org'

gem 'rails', '4.2.3'

gem 'rails-api'
gem 'puma', '~> 2.15.3'
gem 'grape'
gem 'rack-cors'
gem 'roadie'
gem 'roadie-rails'
gem 'sidekiq'
gem 'redis-namespace'

gem 'td-jobs', git: 'https://github.com/talosdigital/TDJobsGem.git'
gem 'td-core', git: 'https://github.com/talosdigital/TDCoreGem.git'
gem 'td-users', git: 'https://github.com/talosdigital/TDUserGem.git'

group :development do
  gem 'spring'
  gem 'rubocop', require: false
end

group :development, :test do
  gem 'faker'
  gem 'rspec-rails'
  gem 'simplecov', require: false
  gem 'ci_reporter_rspec'
end
