var gulp           = require('gulp'),
    path           = require('path'),
    conf           = require(path.join(__dirname, 'conf.js'));

var $ = require('gulp-load-plugins')({
  pattern: ['gulp-*']
});

$.wiredep = require('wiredep').stream;

/**
 * Here, custom pipes with specific functionalities will be build.
 */
/*
 * Pipe for injecting custom CSS and JavaScript into the index.html,
 * notice that we are ignoring the path '../.tmp/app' because of the
 * 'styles.css' file generated by the 'less' task, i.e., the 'styles.css'
 * file will be in the '.tmp/app/assets/css' folder but we don't want
 * that long path in the index.html script, we are only including 'assets/css'.
 */
exports.injectCustom = function() {
  var sources = gulp.src([
    path.join('!' + conf.paths.app, '/lib/**/*'),
    path.join(conf.paths.app, '/**/*.js'),
    path.join(conf.paths.tmp, conf.paths.app, '/assets/css/**/*.css')
  ], { read: false });
  return $.inject(sources, { relative: true, ignorePath: '../.tmp/app' });
};

/*
 * Pipe for injecting custom CSS and JavaScript into the index.html
 */
exports.injectVendor = function() {
  return $.wiredep();
};
